// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hellomicro.proto

package HelloMicro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for HelloMicroService service

func NewHelloMicroServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for HelloMicroService service

type HelloMicroService interface {
	HelloMicro(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type helloMicroService struct {
	c    client.Client
	name string
}

func NewHelloMicroService(name string, c client.Client) HelloMicroService {
	return &helloMicroService{
		c:    c,
		name: name,
	}
}

func (c *helloMicroService) HelloMicro(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "HelloMicroService.HelloMicro", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloMicroService service

type HelloMicroServiceHandler interface {
	HelloMicro(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterHelloMicroServiceHandler(s server.Server, hdlr HelloMicroServiceHandler, opts ...server.HandlerOption) error {
	type helloMicroService interface {
		HelloMicro(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type HelloMicroService struct {
		helloMicroService
	}
	h := &helloMicroServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&HelloMicroService{h}, opts...))
}

type helloMicroServiceHandler struct {
	HelloMicroServiceHandler
}

func (h *helloMicroServiceHandler) HelloMicro(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.HelloMicroServiceHandler.HelloMicro(ctx, in, out)
}
