// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/test1.proto

package test1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for T1Service service

type T1Service interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type t1Service struct {
	c    client.Client
	name string
}

func NewT1Service(name string, c client.Client) T1Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "t1service"
	}
	return &t1Service{
		c:    c,
		name: name,
	}
}

func (c *t1Service) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "T1Service.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for T1Service service

type T1ServiceHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterT1ServiceHandler(s server.Server, hdlr T1ServiceHandler, opts ...server.HandlerOption) error {
	type t1Service interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type T1Service struct {
		t1Service
	}
	h := &t1ServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&T1Service{h}, opts...))
}

type t1ServiceHandler struct {
	T1ServiceHandler
}

func (h *t1ServiceHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.T1ServiceHandler.Hello(ctx, in, out)
}
