name: Learning-go
on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2 #使用 github 官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      - name: Use Upload
        uses: actions/upload-artifact@v2
        with:
          name: Upload Jsonnet File
          path: packer/ubuntu1804.json

      - name: deploy file to server
        uses: laizhenxing/learning-go@master
        with:
            useranem: 'root'
            host: '${{ secrets.PRIVATE_SREVER }}'
            key: '${{ secrets.ACCESS_TOKEN }}'
            port: 22
            #local_path: '.'
            remote_path: '/root/go'
